export const GET_ALL_CHANNELS = 'GET_ALL_CHANNELS';
export const GET_ALL_MUTED_CHANNELS = 'GET_ALL_MUTED_CHANNELS';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_BY_MESSAGE = 'FILTER_BY_MESSAGE';
export const FILTER_MESSAGE_IN_CHANNEL = 'FILTER_MESSAGE_IN_CHANNEL';
export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';
export const SET_SEARCH_CHANNEL = 'SET_SEARCH_CHANNEL';
export const SEARCH_MESSAGE_IN_CHANNEL = 'SEARCH_MESSAGE_IN_CHANNEL';
export const RESET_CHANNEL_SEARCH = 'RESET_CHANNEL_SEARCH';

export const CLIENT_CONNECTION = 'CLIENT_CONNECTION';
export const CLIENT_ERROR = 'CLIENT_ERROR';

// MESSAGES
export const MESSAGE_INPUT = 'MESSAGE_INPUT';
export const MESSAGE_DRAFT = 'MESSAGE_DRAFT';
export const SET_MESSAGE = 'SET_MESSAGE';
export const PREVIOUS_MESSAGES_PAGINATION = 'PREVIOUS_MESSAGES_PAGINATION';
export const SET_MESSAGE_TO_CHANNEL = 'SET_MESSAGE_TO_CHANNEL';
export const MESSAGE_ACTIONS = 'MESSAGE_ACTIONS';
export const ATTACH_IMAGE = 'ATTACH_IMAGE';
export const REMOVE_SELECTED_MESSAGES = 'REMOVE_SELECTED_MESSAGES';
export const DE_SELECTED_MESSAGES = 'DE_SELECTED_MESSAGES';
export const SET_MODAL = 'SET_MODAL';
export const MEMBER_INFO_MODAL = 'MEMBER_INFO_MODAL';
export const DELETE_PINNED_MESSAGE_MODAL = 'DELETE_PINNED_MESSAGE_MODAL';
export const PINNED_MESSAGES_MODAL = 'PINNED_MESSAGES_MODAL';
export const ACTIVE_CHANNEL_MEMBERS = 'ACTIVE_CHANNEL_MEMBERS';
export const LEAVE_CHANNEL = 'LEAVE_CHANNEL';
export const CREATE_CHANNEL_FORM_MODAL = 'CREATE_CHANNEL_FORM_MODAL';
export const CREATE_CHANNEL_DETAILS = 'CREATE_CHANNEL_DETAILS';
export const QUOTED_MESSAGE_ID = 'QUOTED_MESSAGE_ID';
export const MESSAGE_ADD_TO_CHANNEL = 'MESSAGE_ADD_TO_CHANNEL';
export const MEMBER_ADD_TO_CHANNEL = 'MEMBER_ADD_TO_CHANNEL';
export const ADD_MESSAGE_CHANNEL_LOCAL = 'ADD_MESSAGE_CHANNEL_LOCAL';
export const UPDATE_MESSAGE_CHANNEL_LOCAL = 'UPDATE_MESSAGE_CHANNEL_LOCAL';
export const PINNED_MESSAGE = 'PINNED_MESSAGE';
export const PINNED_MESSAGES_BY_CHANNEL = 'PINNED_MESSAGES_BY_CHANNEL';
export const PINNED_MESSAGE_MODAL = 'PINNED_MESSAGE_MODAL';
export const REPLY_MESSAGE_FLAG = 'REPLY_MESSAGE_FLAG';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const IS_USER_BANNED = 'IS_USER_BANNED';
export const CHANNEL_MEMBERS = 'CHANNEL_MEMBERS';

//USER_EVENTS
export const USER_EVENT_START = 'USER_EVENT_START';
export const USER_EVENT_STOP = 'USER_EVENT_STOP';
