/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_appsync_graphqlEndpoint": "https://34kgxnzbgjfgngbl27tykpssmm.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_appsync_apiKey": "da2-od76fydcgzemzelgbphp77kmni",
  "aws_cloud_logic_custom": [
      {
          "name": "ThinkSabioRESTAPI",
          "endpoint": "https://i8v85xkvyi.execute-api.us-east-1.amazonaws.com/test",
          "region": "us-east-1"
      }
  ],
  "aws_cognito_identity_pool_id": "us-east-1:5982b8e2-4a9d-4a44-98d2-36b181641e0d",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_2YnPYeIHV",
  "aws_user_pools_web_client_id": "7dmhp9bf815m5dimpf8lsoa8to",
  "cookieStorage": {
      // - Cookie domain (only required if cookieStorage is provided)
        "domain": '.test.thinksabio.com',
      // (optional) - Cookie path
        "path": '/',
      // (optional) - Cookie expiration in days
        "expires": 365,
      // (optional) - See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
        "sameSite": "strict",
                  // (optional) - Cookie secure flag
      // Either true or false, indicating if the cookie transmission requires a secure protocol (https).
        "secure": true
      },
  "oauth": {
      "domain": "thinksabio-new-test.auth.us-east-1.amazoncognito.com",
      "scope": [
          "phone",
          "email",
          "openid",
          "profile",
          "aws.cognito.signin.user.admin"
      ],
      "redirectSignIn": "https://www.test.thinksabio.com/",
      "redirectSignOut": "https://www.test.thinksabio.com/",
      "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;